spring:
  webflux:
    base-path: /

reactor:
  netty:
    http:
      server:
        accessLogEnabled: true

de.havemann.lukas.transformer:
  url: https://codechallenge.mobilelab.io/v1/mytoys/navigation
  apitoken: N8Nx0OwOvo1iuN2ZkFHZlyVKBVgoIcy4tUHMppO5

management.endpoints.web.exposure.include: "*"